export const experienceData = [
    {
        title: "Full Stack Developer",
        company: "Temerity Analytics",
        companyUrl: "https://temerityanalytics.com/",
        companyLogo: "/company_logos/temerityanalytics.png",
        location: "Toronto, ON",
        dates: "Incoming May 2026",
        summary: "Full-stack web development and data engineering",
        technologies: [
            "Python",
            "Django",
            "PostgreSQL",
            "Angular",
            "Docker",
            "REST API",
            "TypeScript",
            "CSS",
            "Svelte",
        ],
        description: [
            "Engineered end-to-end data visualization and reporting modules using PostgreSQL, Django, and Angular, transforming complex client datasets into actionable dashboards and contributing 20K+ lines of production code",
            "Developed secure Django REST API endpoints with serializers, role-based access controls, and request validation, supporting 50+ backend routes while maintaining sub-100ms average response times",
            "Optimized PostgreSQL data models through schema design, query tuning, and compound indexing, reducing query latency by 40% and enabling support for 10x larger analytics datasets",
        ],
    },
    {
        title: "AI Engineering Intern",
        company: "Cache",
        companyUrl: "https://cacheinyourcloset.com",
        companyLogo: "/company_logos/cache.jpg",
        location: "Remote, Toronto, ON",
        dates: "Feb 2026 - Present",
        summary: "Payments, authentication, and full-stack across web and iOS",
        technologies: ["React", "Swift", "Stripe", "PostgreSQL", "Supabase"],
        description: [
            "Led end-to-end deployment of Stripe payment processing, authentication, and user management across a React web app and iOS Swift app, supporting 100+ users and 1,500+ transactions",
            "Designed and optimized a PostgreSQL database on Supabase powering 50+ API endpoints, achieving sub-100ms response times through caching, denormalization, and memoization",
            "Delivered 10,000+ lines of production code across the full stack and mobile app, driving $5,000+ in revenue and enabling 5x user growth through feature development and performance improvements",
        ],
    },
    {
        title: "Software Engineering Intern",
        company: "Local Reach",
        companyUrl: "https://thelocalreach.ca",
        companyLogo: "/company_logos/localreach.jpg",
        location: "Kingston, ON",
        dates: "Nov 2024 - Mar 2025",
        summary: "Full-stack, web performance, computer vision, and ML pipelines",
        technologies: ["Next.js", "YOLO", "OpenCV", "Python", "TensorFlow"],
        description: [
            "Refactored the website to leverage SSR and SSG techniques, reducing client-side bundle size by 68% and improving initial page load time from 2.8s to 0.9s.",
            "Developed YOLO computer vision pipeline for automated TV display recognition in retail stores, achieving 30+ FPS throughput with sub-500ms latency through OpenCV preprocessing; technology acquired by Taiv (YC W20)",
            "Engineered a neural network audio classifier using MFCC, mel-spectrogram, chroma, and tonnetz features using librosa, achieving 92% accuracy with a 3-layer dense architecture optimized through 64-epoch training",
        ],
    },
    {
        title: "Charity CEO and Lead Developer",
        company: "Baobab",
        companyLogo: "/company_logos/baobab.jpg",
        location: "Toronto, ON",
        dates: "Dec 2024 - Aug 2025",
        summary: "Full-stack donation platform for charities in my communities",
        technologies: ["MERN", "JWT", "MongoDB", "React"],
        description: [
            "Built and deployed a full-stack MERN donation platform serving 10 charitable organizations with 90+ active users, contributing 9K+ lines of production code that facilitated $1,000+ in donations",
            "Implemented JWT-based authentication with bcrypt password hashing and RBAC protecting 50+ API endpoints while maintaining sub-100ms average response time",
            "Optimized MongoDB schema with compound indexes on 3 core collections achieving 40% faster query performance and supporting 10x data volume scalability through denormalization strategies",
        ],
    },
];
